apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.erida.service.type }}
  selector:
    app: {{ .Chart.Name }}-pod
  ports:
    - port: {{ .Values.erida.service.port }}
      protocol: TCP
      targetPort: {{ .Values.erida.service.port }}
