name: publish

on:
  push:
    branches: [ 'master' ]

jobs:
  publish:
    name: publish
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6
      - run: ko build --platform=linux/amd64 --bare ./cmd/erida/...